apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-audit-pvc
  namespace: secret-manager
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage-tools